[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx prisma generate && npx prisma migrate reset --force && npm run build"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100 