[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx prisma migrate deploy && npm run build"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100 